// Controlled vocabulary for the synthetic RAG corpus. Mirrors SPEC.md sections 4-8 and 12-13.

export const START_DATE = "2025-01-01";
export const END_DATE = "2026-09-28";

export const DAY_PATTERNS = {
  D1: ["Sat", "Mon", "Wed"],
  D2: ["Sun", "Tue", "Thu"],
  D3: ["Sat", "Sun", "Mon", "Tue", "Wed"],
};

export const SLOT_TEMPLATES = {
  S1: ["09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM"],
  S2: ["02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM", "04:00 PM", "04:30 PM"],
  S3: ["10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "03:00 PM", "03:30 PM", "04:00 PM", "04:30 PM"],
};

export const DAY_NAMES = {
  Sat: "Saturday", Sun: "Sunday", Mon: "Monday", Tue: "Tuesday", Wed: "Wednesday", Thu: "Thursday", Fri: "Friday",
};

export const SPECIALIZATIONS = [
  { id: "SPEC-01", name: "General Medicine", fee: 600, room: 1, prepTip: "bring a record of your temperature readings", referTo: ["Gastroenterology", "Pulmonology"] },
  { id: "SPEC-02", name: "Cardiology", fee: 1200, room: 2, prepTip: "bring any previous ECG reports and a list of your blood pressure readings", referTo: ["Endocrinology"] },
  { id: "SPEC-03", name: "Pulmonology", fee: 1000, room: 3, prepTip: "bring your inhalers so the doctor can check your technique", referTo: ["ENT"] },
  { id: "SPEC-04", name: "Gastroenterology", fee: 1000, room: 4, prepTip: "note what you ate in the days before your symptoms started", referTo: ["General Medicine"] },
  { id: "SPEC-05", name: "Endocrinology", fee: 1000, room: 5, prepTip: "bring your home blood sugar records", referTo: ["Cardiology", "Ophthalmology"] },
  { id: "SPEC-06", name: "Dermatology", fee: 800, room: 6, prepTip: "do not apply creams to the affected skin on the day of the visit", referTo: ["Endocrinology"] },
  { id: "SPEC-07", name: "Orthopedics", fee: 1000, room: 7, prepTip: "wear loose clothing and bring any previous X-rays", referTo: ["Neurology"] },
  { id: "SPEC-08", name: "Neurology", fee: 1200, room: 8, prepTip: "bring a headache or symptom diary", referTo: ["Ophthalmology", "Psychiatry"] },
  { id: "SPEC-09", name: "ENT", fee: 800, room: 9, prepTip: "note when your symptoms started and what makes them worse", referTo: ["Pulmonology"] },
  { id: "SPEC-10", name: "Ophthalmology", fee: 800, room: 10, prepTip: "bring your current glasses", referTo: ["Neurology"] },
  { id: "SPEC-11", name: "Obstetrics and Gynecology", fee: 1000, room: 11, prepTip: "note the date of your last period", referTo: ["Endocrinology"] },
  { id: "SPEC-12", name: "Psychiatry", fee: 1200, room: 12, prepTip: "note your main worries and your sleep pattern for one week", referTo: ["Neurology"] },
];

// [ref, name, specialization, experience years, languages]
const DOCTOR_ROWS = [
  ["DOC-001", "Dr. Farhana Kabir", "General Medicine", 9, "Bangla, English"],
  ["DOC-002", "Dr. Tanvir Ahmed", "General Medicine", 6, "Bangla, English"],
  ["DOC-003", "Dr. Nusrat Jahan", "General Medicine", 17, "Bangla, English, Hindi"],
  ["DOC-004", "Dr. Mahmudul Hasan", "Cardiology", 12, "Bangla, English"],
  ["DOC-005", "Dr. Sabrina Chowdhury", "Cardiology", 8, "Bangla, English"],
  ["DOC-006", "Dr. Rafiqul Islam", "Cardiology", 22, "Bangla, English, Arabic"],
  ["DOC-007", "Dr. Shirin Akter", "Pulmonology", 10, "Bangla, English"],
  ["DOC-008", "Dr. Arif Hossain", "Pulmonology", 7, "Bangla, English"],
  ["DOC-009", "Dr. Kamrul Hasan", "Pulmonology", 19, "Bangla, English"],
  ["DOC-010", "Dr. Nasrin Sultana", "Gastroenterology", 11, "Bangla, English"],
  ["DOC-011", "Dr. Imran Kabir", "Gastroenterology", 5, "Bangla, English"],
  ["DOC-012", "Dr. Zahid Hasan", "Gastroenterology", 18, "Bangla, English, Hindi"],
  ["DOC-013", "Dr. Rumana Haque", "Endocrinology", 13, "Bangla, English"],
  ["DOC-014", "Dr. Saiful Alam", "Endocrinology", 6, "Bangla, English"],
  ["DOC-015", "Dr. Lubna Rahman", "Endocrinology", 20, "Bangla, English"],
  ["DOC-016", "Dr. Tahmina Begum", "Dermatology", 9, "Bangla, English"],
  ["DOC-017", "Dr. Asif Mahmud", "Dermatology", 4, "Bangla, English"],
  ["DOC-018", "Dr. Sadia Islam", "Dermatology", 15, "Bangla, English"],
  ["DOC-019", "Dr. Mostafizur Rahman", "Orthopedics", 14, "Bangla, English"],
  ["DOC-020", "Dr. Jannatul Ferdous", "Orthopedics", 7, "Bangla, English"],
  ["DOC-021", "Dr. Habibur Rahman", "Orthopedics", 24, "Bangla, English"],
  ["DOC-022", "Dr. Selina Parvin", "Neurology", 12, "Bangla, English"],
  ["DOC-023", "Dr. Rezaul Karim", "Neurology", 8, "Bangla, English"],
  ["DOC-024", "Dr. Moinul Haque", "Neurology", 21, "Bangla, English, Hindi"],
  ["DOC-025", "Dr. Fahmida Yasmin", "ENT", 10, "Bangla, English"],
  ["DOC-026", "Dr. Shahadat Hossain", "ENT", 6, "Bangla, English"],
  ["DOC-027", "Dr. Towhid Alam", "ENT", 16, "Bangla, English"],
  ["DOC-028", "Dr. Shamima Nasrin", "Ophthalmology", 11, "Bangla, English"],
  ["DOC-029", "Dr. Anisur Rahman", "Ophthalmology", 5, "Bangla, English"],
  ["DOC-030", "Dr. Mehedi Hasan", "Ophthalmology", 18, "Bangla, English"],
  ["DOC-031", "Dr. Rokeya Khatun", "Obstetrics and Gynecology", 15, "Bangla, English"],
  ["DOC-032", "Dr. Sharmin Akter", "Obstetrics and Gynecology", 8, "Bangla, English"],
  ["DOC-033", "Dr. Nazma Begum", "Obstetrics and Gynecology", 23, "Bangla, English"],
  ["DOC-034", "Dr. Ishrat Jahan", "Psychiatry", 10, "Bangla, English"],
  ["DOC-035", "Dr. Faisal Karim", "Psychiatry", 7, "Bangla, English"],
  ["DOC-036", "Dr. Mahbuba Rahman", "Psychiatry", 19, "Bangla, English"],
];

export const DOCTORS = DOCTOR_ROWS.map(([ref, name, specialization, experienceYears, languages], index) => {
  const spec = SPECIALIZATIONS.find((s) => s.name === specialization);
  const position = index % 3;
  const dayPattern = ["D1", "D2", "D3"][position];
  const slotTemplate = ["S1", "S2", "S3"][position];
  return {
    ref,
    name,
    specialization,
    specializationId: spec.id,
    dayPattern,
    days: DAY_PATTERNS[dayPattern],
    slotTemplate,
    slots: SLOT_TEMPLATES[slotTemplate],
    fee: spec.fee + (position === 2 ? 200 : 0),
    senior: position === 2,
    room: `Room ${spec.room}0${position + 1}`,
    experienceYears,
    languages,
  };
});

const m = (name, dosage, frequency, duration) => ({ name, dosage, frequency, duration });

// vital: [kind, min, max]. Kinds are rendered by generate-manifest.mjs.
export const DIAGNOSES = [
  // SPEC-01 General Medicine
  {
    id: "DX-0101", spec: "General Medicine", name: "Viral fever", age: [18, 70], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["fever for two to three days", "aching all over the body", "feeling very tired", "a mild headache"],
    regimens: [[m("Paracetamol", "500 mg", "Every 6 hours as needed", "5 days")]],
    advice: "drink plenty of fluids; rest at home for three days; sponge with lukewarm water if the fever is high",
    rxAdvice: "take paracetamol only when the temperature is above 100°F; do not take more than four doses in 24 hours; drink plenty of fluids",
    followUp: "3 days if the fever does not settle", tests: "a complete blood count",
    triggers: ["started after a crowded bus journey from {place}", "began after several relatives in {place} had the same fever", "started after getting soaked in heavy rain in {place}"],
    atypical: "fever with marked pain in both wrists but almost no body ache",
    vital: ["temp", 100.4, 102.8],
  },
  {
    id: "DX-0102", spec: "General Medicine", name: "Typhoid fever", age: [18, 60], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["a fever that climbs a little higher every day for over a week", "dull discomfort in the belly", "no appetite", "a coated tongue"],
    regimens: [[m("Azithromycin", "500 mg", "Once daily", "7 days"), m("Paracetamol", "500 mg", "Every 6 hours as needed", "5 days")]],
    advice: "eat soft home-cooked food; drink boiled or bottled water only; avoid street food",
    rxAdvice: "complete the full azithromycin course even if the fever settles; take paracetamol only for fever; drink safe water only",
    followUp: "7 days with a repeat blood count", tests: "a blood culture and complete blood count",
    triggers: ["began a few days after eating street food at a fair in {place}", "started after drinking roadside juice in {place}", "began after a work trip to {place} where the water supply was unsafe"],
    atypical: "constipation and evening confusion with only a low-grade fever",
    vital: ["temp", 101.0, 103.4],
  },
  {
    id: "DX-0103", spec: "General Medicine", name: "Dengue fever", age: [18, 65], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["a sudden high fever", "pain behind the eyes", "severe aching in the bones and muscles", "a faint rash on the arms"],
    regimens: [[m("Paracetamol", "500 mg", "Every 6 hours as needed", "5 days"), m("Oral rehydration salts", "1 sachet in 500 ml water", "Three times daily", "5 days")]],
    advice: "drink at least three litres of fluid a day; avoid ibuprofen and aspirin; repeat the platelet count in 48 hours; go to hospital at once for bleeding gums, black stools, or severe belly pain",
    rxAdvice: "use paracetamol only for fever and pain; do not take ibuprofen or aspirin; mix each oral rehydration salts sachet in 500 ml of clean water",
    followUp: "48 hours with a repeat platelet count", tests: "a dengue NS1 antigen test and complete blood count",
    triggers: ["started during the monsoon after mosquitoes bred in water tanks near {place}", "began after a neighbour in {place} was admitted with dengue", "started after a week of stagnant rainwater around the house in {place}"],
    atypical: "fever that settled on day four, followed by new tiredness and mild gum bleeding",
    vital: ["platelet", 60, 140],
  },
  {
    id: "DX-0104", spec: "General Medicine", name: "Iron deficiency anaemia", age: [18, 60], sex: "female70", chronic: true, febrile: false, canDefer: true,
    cues: ["constant tiredness", "getting breathless on the stairs", "looking pale", "brittle nails"],
    regimens: [[m("Ferrous sulfate", "200 mg", "Twice daily", "3 months"), m("Folic acid", "5 mg", "Once daily", "3 months")]],
    advice: "eat more lentils, spinach, liver, and eggs; avoid tea within an hour of meals",
    rxAdvice: "take the iron tablet with water or orange juice, not with tea or milk; dark stools are expected while taking iron",
    followUp: "6 weeks with a repeat haemoglobin", tests: "a complete blood count and serum ferritin",
    triggers: ["noticed after months of skipping lunch during long shifts in {place}", "worsened after a long spell of poor meals while living alone in {place}", "started after a stomach illness during a stay in {place}"],
    atypical: "a craving to chew ice and a sore smooth tongue with little tiredness",
    vital: ["hb", 7.8, 10.4],
  },
  // SPEC-02 Cardiology
  {
    id: "DX-0201", spec: "Cardiology", name: "Essential hypertension", age: [30, 85], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["headaches on waking", "a high reading on a pharmacy machine", "no other complaints", "occasional dizziness"],
    regimens: [[m("Amlodipine", "5 mg", "Once daily", "Ongoing")], [m("Losartan", "50 mg", "Once daily", "Ongoing")]],
    advice: "cut down on salt, pickles, and dried fish; walk 30 minutes daily; check blood pressure at home twice a week",
    rxAdvice: "take the tablet at the same time every morning; do not stop it when the readings improve; report any ankle swelling",
    followUp: "1 month with home blood pressure readings", tests: "serum creatinine, electrolytes, and an ECG",
    triggers: ["found during a free health camp in {place}", "noticed after a stressful month of overtime in {place}", "picked up at a pharmacy in {place} while buying other medicines"],
    atypical: "nosebleeds and blurred vision with no headache",
    vital: ["bp", 145, 178, 92, 108],
  },
  {
    id: "DX-0202", spec: "Cardiology", name: "Stable angina", age: [45, 85], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["chest tightness when walking fast or climbing", "a heavy feeling in the chest that eases with rest within minutes", "breathlessness on effort"],
    regimens: [[m("Aspirin", "75 mg", "Once daily", "Ongoing"), m("Atorvastatin", "20 mg", "At bedtime", "Ongoing"), m("Glyceryl trinitrate spray", "1 puff", "As needed", "Ongoing")]],
    advice: "avoid heavy exertion until review; walk 20 minutes daily on flat ground; stop smoking",
    rxAdvice: "take aspirin after breakfast; use the spray under the tongue at the start of chest tightness and sit down; if pain lasts more than 15 minutes call 999",
    followUp: "2 weeks with an ECG and fasting lipid profile", tests: "an ECG, exercise tolerance test, and fasting lipid profile",
    triggers: ["first noticed while climbing to a fourth-floor flat in {place}", "started while carrying shopping bags uphill in {place}", "first felt while rushing to catch a train in {place}"],
    atypical: "jaw and left arm discomfort on effort with no chest pain",
    vital: ["bp", 132, 158, 82, 96],
  },
  {
    id: "DX-0203", spec: "Cardiology", name: "Dyslipidaemia", age: [30, 80], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["high cholesterol on a routine test", "a father who had a heart attack at 55", "no symptoms"],
    regimens: [[m("Atorvastatin", "10 mg", "At bedtime", "3 months")], [m("Rosuvastatin", "10 mg", "At bedtime", "3 months")]],
    advice: "reduce fried food, red meat, and ghee; walk 30 minutes daily; aim to lose 3 kg",
    rxAdvice: "take the tablet at night; report any unexplained muscle pain",
    followUp: "3 months with a repeat lipid profile", tests: "a fasting lipid profile and liver function tests",
    triggers: ["found in an office health check in {place}", "found on a pre-employment test in {place}", "found after a relative's heart attack in {place} prompted testing"],
    atypical: "yellowish fatty deposits around the eyelids noticed by the family",
    vital: ["ldl", 4.2, 6.1],
  },
  {
    id: "DX-0204", spec: "Cardiology", name: "Atrial fibrillation", age: [55, 85], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["an irregular fast heartbeat", "fluttering in the chest", "dizzy spells", "getting tired easily"],
    regimens: [[m("Bisoprolol", "2.5 mg", "Once daily", "Ongoing"), m("Apixaban", "5 mg", "Twice daily", "Ongoing")]],
    advice: "limit tea and coffee; avoid alcohol; report any fainting at once",
    rxAdvice: "take apixaban twelve hours apart and never skip doses; report any unusual bleeding or black stools",
    followUp: "2 weeks with an ECG and kidney function tests", tests: "an ECG, echocardiogram, and thyroid function tests",
    triggers: ["first noticed while resting after a family lunch in {place}", "started after a sleepless night travelling to {place}", "first felt while watching television at home in {place}"],
    atypical: "no palpitations at all, only breathlessness and ankle swelling",
    vital: ["pulse_irregular", 112, 148],
  },
  // SPEC-03 Pulmonology
  {
    id: "DX-0301", spec: "Pulmonology", name: "Bronchial asthma", age: [18, 70], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["wheezing", "coughing at night", "a tight chest in dust or cold air"],
    regimens: [[m("Salbutamol inhaler", "2 puffs", "Every 6 hours as needed", "Ongoing"), m("Budesonide-formoterol inhaler", "2 puffs", "Twice daily", "3 months")]],
    advice: "avoid dust and smoke; keep the bedroom well aired; learn the correct inhaler technique",
    rxAdvice: "use the reliever inhaler for sudden wheeze; rinse the mouth after the preventer inhaler; seek urgent care if the reliever is needed more often than every 4 hours",
    followUp: "1 month to check inhaler technique", tests: "spirometry and a peak flow diary",
    triggers: ["worse since construction dust started near home in {place}", "flared during the winter smog in {place}", "started after moving into a damp flat in {place}"],
    atypical: "only a dry night cough for months with no wheeze",
    vital: ["spo2", 92, 97],
  },
  {
    id: "DX-0302", spec: "Pulmonology", name: "COPD exacerbation", age: [50, 85], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["breathlessness worse for several days", "more sputum than usual", "a long history of smoking", "wheezing on walking"],
    regimens: [[m("Tiotropium inhaler", "1 puff", "Once daily", "Ongoing"), m("Prednisolone", "40 mg", "Once daily", "5 days"), m("Amoxicillin-clavulanate", "625 mg", "Three times daily", "7 days")]],
    advice: "stop smoking completely; avoid cooking smoke; take the yearly flu vaccine",
    rxAdvice: "take prednisolone after breakfast; complete the antibiotic course; use the inhaler every morning",
    followUp: "1 week, sooner if breathing worsens", tests: "a chest X-ray and spirometry",
    triggers: ["worsened after a cold caught at a crowded market in {place}", "flared after rubbish was burned near home in {place}", "worsened during the dusty dry season in {place}"],
    atypical: "confusion and sleepiness with only mild breathlessness",
    vital: ["spo2", 86, 92],
  },
  {
    id: "DX-0303", spec: "Pulmonology", name: "Community-acquired pneumonia", age: [18, 80], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["fever", "cough with yellow or green sputum", "sharp chest pain on breathing in"],
    regimens: [[m("Amoxicillin", "500 mg", "Three times daily", "7 days"), m("Azithromycin", "500 mg", "Once daily", "3 days"), m("Paracetamol", "500 mg", "Every 6 hours as needed", "5 days")]],
    advice: "rest and drink plenty of fluids; return at once if breathing becomes difficult",
    rxAdvice: "complete both antibiotic courses; take paracetamol for fever or chest pain only",
    followUp: "3 days for review and a chest X-ray in 6 weeks", tests: "a chest X-ray and complete blood count",
    triggers: ["began after caring for a sick relative in {place}", "started after a long cold boat trip near {place}", "began a week after a flu-like illness in {place}"],
    atypical: "belly pain and diarrhoea with only a mild cough",
    vital: ["temp", 101.2, 103.6],
  },
  {
    id: "DX-0304", spec: "Pulmonology", name: "Acute bronchitis", age: [18, 75], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["a cough for one to two weeks after a cold", "mild wheeze", "no high fever", "a sore chest from coughing"],
    regimens: [[m("Dextromethorphan syrup", "10 ml", "Three times daily", "5 days"), m("Paracetamol", "500 mg", "Every 6 hours as needed", "3 days")]],
    advice: "drink warm fluids; use steam inhalation twice daily; avoid smoke",
    rxAdvice: "do not take the cough syrup with alcohol; the syrup may cause drowsiness",
    followUp: "2 weeks if the cough continues", tests: "no tests unless the cough lasts over three weeks",
    triggers: ["began after a cold that went round the office in {place}", "started after a dusty road trip to {place}", "began after a family wedding in {place}"],
    atypical: "a hoarse voice as the main complaint with only occasional cough",
    vital: ["temp", 98.8, 100.0],
  },
  // SPEC-04 Gastroenterology
  {
    id: "DX-0401", spec: "Gastroenterology", name: "Gastro-oesophageal reflux disease", age: [18, 80], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["burning behind the breastbone after meals", "a sour taste in the mouth", "symptoms worse when lying down"],
    regimens: [[m("Omeprazole", "20 mg", "Once daily before breakfast", "1 month")]],
    advice: "eat smaller meals; avoid oily and spicy food late at night; raise the head of the bed",
    rxAdvice: "take omeprazole 30 minutes before breakfast",
    followUp: "1 month", tests: "no tests unless symptoms persist",
    triggers: ["worse since a job change in {place} meant late heavy dinners", "worse after weeks of fried snacks at tea stalls in {place}", "began after gaining weight while working from home in {place}"],
    atypical: "a long-standing dry cough and hoarse voice with little heartburn",
    vital: ["bmi", 26.0, 32.5],
  },
  {
    id: "DX-0402", spec: "Gastroenterology", name: "Peptic ulcer disease", age: [20, 75], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["gnawing pain in the upper belly", "pain that wakes them at night", "pain that eases after eating"],
    regimens: [[m("Omeprazole", "20 mg", "Twice daily", "14 days"), m("Amoxicillin", "1 g", "Twice daily", "14 days"), m("Clarithromycin", "500 mg", "Twice daily", "14 days")]],
    advice: "avoid painkillers such as ibuprofen; stop smoking; eat regular meals",
    rxAdvice: "take all three medicines for the full 14 days; take omeprazole before meals; the antibiotics may cause a metallic taste",
    followUp: "4 weeks with a stool H. pylori test", tests: "a stool H. pylori antigen test",
    triggers: ["started after weeks of taking painkillers for back pain in {place}", "began during a stressful exam period in {place}", "started after irregular meals on night shifts in {place}"],
    atypical: "no pain, only early fullness and vomiting after meals",
    vital: ["pain", 5, 8],
  },
  {
    id: "DX-0403", spec: "Gastroenterology", name: "Irritable bowel syndrome", age: [18, 55], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["cramping belly pain", "stools that switch between loose and hard", "bloating", "symptoms worse with stress"],
    regimens: [[m("Mebeverine", "135 mg", "Three times daily", "1 month")]],
    advice: "eat regular meals; keep a food diary; reduce tea, fizzy drinks, and beans",
    rxAdvice: "take mebeverine 20 minutes before meals",
    followUp: "6 weeks with the food diary", tests: "a complete blood count and stool examination",
    triggers: ["worse since starting a high-pressure job in {place}", "began after a bout of food poisoning in {place}", "flares on long commutes through traffic in {place}"],
    atypical: "urgent loose stools every morning with little pain",
    vital: ["pain", 3, 6],
  },
  {
    id: "DX-0404", spec: "Gastroenterology", name: "Acute gastroenteritis", age: [18, 75], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["loose watery stools", "vomiting", "belly cramps", "feeling weak"],
    regimens: [[m("Oral rehydration salts", "1 sachet in 500 ml water", "After each loose stool", "3 days"), m("Ondansetron", "4 mg", "Every 8 hours as needed", "3 days"), m("Zinc", "20 mg", "Once daily", "10 days")]],
    advice: "drink small sips of fluid often; eat rice, bananas, and toast; wash hands before eating",
    rxAdvice: "mix each sachet in 500 ml of clean water and drink it after every loose stool; take ondansetron only if vomiting",
    followUp: "2 days if the stools do not settle", tests: "a stool examination if it persists",
    triggers: ["started after eating biryani at a roadside shop in {place}", "began after a picnic in {place}", "started after drinking tap water on a trip to {place}"],
    atypical: "high fever and blood in the stool with little vomiting",
    vital: ["pulse", 96, 118],
  },
  // SPEC-05 Endocrinology
  {
    id: "DX-0501", spec: "Endocrinology", name: "Type 2 diabetes mellitus", age: [30, 85], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["always feeling thirsty", "passing urine often", "losing weight without trying", "cuts that heal slowly"],
    regimens: [[m("Metformin", "500 mg", "Twice daily", "Ongoing")], [m("Metformin", "500 mg", "Twice daily", "Ongoing"), m("Gliclazide", "80 mg", "Once daily before breakfast", "Ongoing")]],
    advice: "reduce rice portions and sweets; walk briskly 30 minutes five days a week; check fasting sugar twice weekly; check the feet daily",
    rxAdvice: "take the tablets with meals to avoid stomach upset; eat regular meals to prevent low sugar",
    followUp: "3 months with HbA1c", tests: "HbA1c, fasting glucose, and urine albumin",
    triggers: ["sugar readings rose during a busy season at work in {place}", "found during a routine test before a trip to {place}", "noticed after a relative in {place} was diagnosed and advised testing"],
    atypical: "repeated fungal skin infections as the only complaint",
    vital: ["glucose", 7.4, 13.8],
  },
  {
    id: "DX-0502", spec: "Endocrinology", name: "Hypothyroidism", age: [25, 75], sex: "female70", chronic: true, febrile: false, canDefer: false,
    cues: ["weight gain", "always feeling cold", "dry skin", "feeling slow and tired"],
    regimens: [[m("Levothyroxine", "50 mcg", "Once daily before breakfast", "Ongoing")]],
    advice: "keep a regular sleep routine; eat a balanced diet",
    rxAdvice: "take levothyroxine on an empty stomach 30 minutes before breakfast; do not take it with calcium or iron tablets",
    followUp: "6 weeks with a repeat TSH", tests: "TSH and free T4",
    triggers: ["noticed when a cold winter in {place} felt harder than usual", "found during tests for tiredness after moving to {place}", "noticed by colleagues in {place} who remarked on weight gain"],
    atypical: "a hoarse voice and low mood with little weight change",
    vital: ["tsh", 7.5, 18.0],
  },
  {
    id: "DX-0503", spec: "Endocrinology", name: "Hyperthyroidism", age: [20, 60], sex: "female70", chronic: true, febrile: false, canDefer: false,
    cues: ["losing weight despite eating well", "a racing heart", "hating the heat", "shaky hands"],
    regimens: [[m("Carbimazole", "10 mg", "Twice daily", "1 month"), m("Propranolol", "10 mg", "Three times daily", "1 month")]],
    advice: "avoid excess tea and coffee; rest when the heart races",
    rxAdvice: "report a sore throat or fever at once while taking carbimazole; do not stop propranolol suddenly",
    followUp: "4 weeks with thyroid function tests", tests: "TSH, free T4, and a complete blood count",
    triggers: ["noticed during a hot summer in {place}", "began after a stressful family event in {place}", "noticed when clothes became loose during a stay in {place}"],
    atypical: "muscle weakness when climbing stairs with no palpitations",
    vital: ["pulse", 104, 128],
  },
  {
    id: "DX-0504", spec: "Endocrinology", name: "Vitamin D deficiency", age: [18, 75], sex: "any", chronic: false, febrile: false, canDefer: true,
    cues: ["aching bones", "low energy", "muscle cramps", "working indoors all day"],
    regimens: [[m("Cholecalciferol", "40000 IU", "Once weekly", "2 months"), m("Calcium carbonate", "500 mg", "Twice daily", "3 months")]],
    advice: "get 20 minutes of morning sunlight daily; eat eggs and fish",
    rxAdvice: "take cholecalciferol on the same day each week with a meal; take calcium after meals",
    followUp: "3 months with a repeat vitamin D level", tests: "serum vitamin D and calcium",
    triggers: ["began after months of night shifts indoors in {place}", "noticed after working in a windowless office in {place}", "started after staying indoors during a long illness in {place}"],
    atypical: "frequent falls and difficulty rising from a chair",
    vital: ["vitd", 8, 18],
  },
  // SPEC-06 Dermatology
  {
    id: "DX-0601", spec: "Dermatology", name: "Atopic eczema", age: [18, 60], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["itchy dry patches on the elbows and knees", "symptoms worse in winter", "scratching at night"],
    regimens: [[m("Hydrocortisone 1% cream", "Apply thin layer", "Twice daily", "7 days"), m("Emollient cream", "Apply thin layer", "Three times daily", "Ongoing")]],
    advice: "use a mild soap; avoid hot baths; wear cotton clothes",
    rxAdvice: "apply hydrocortisone only to red patches and stop after 7 days; use the emollient generously on all dry skin",
    followUp: "2 weeks", tests: "no tests",
    triggers: ["worse since switching to a strong detergent in {place}", "flared during the dry winter in {place}", "started after working with cleaning chemicals in {place}"],
    atypical: "thick darkened skin on the hands with little redness",
    vital: ["lesion", 3, 12],
  },
  {
    id: "DX-0602", spec: "Dermatology", name: "Acne vulgaris", age: [18, 30], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["pimples and blackheads on the face", "spots on the back", "marks left after pimples"],
    regimens: [[m("Benzoyl peroxide 5% gel", "Apply thin layer", "At bedtime", "3 months"), m("Doxycycline", "100 mg", "Once daily", "2 months")]],
    advice: "wash the face twice daily with a gentle cleanser; do not squeeze spots",
    rxAdvice: "apply the gel at night to the whole area; take doxycycline with water and stay upright for 30 minutes; avoid strong sun",
    followUp: "2 months", tests: "no tests",
    triggers: ["worse since exam stress at a university in {place}", "flared after using a heavy face cream bought in {place}", "worse since working in a hot kitchen in {place}"],
    atypical: "deep painful lumps along the jawline only",
    vital: ["spots", 8, 35],
  },
  {
    id: "DX-0603", spec: "Dermatology", name: "Tinea corporis", age: [18, 65], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["a ring-shaped itchy red rash", "a rash with spreading edges", "itch worse in humid weather"],
    regimens: [[m("Clotrimazole 1% cream", "Apply thin layer", "Twice daily", "14 days"), m("Terbinafine", "250 mg", "Once daily", "14 days")]],
    advice: "keep the skin dry; do not share towels; wash clothes in hot water",
    rxAdvice: "apply the cream 2 cm beyond the edge of the rash; continue for the full 14 days even if it clears",
    followUp: "2 weeks", tests: "a skin scraping if it does not improve",
    triggers: ["started after sharing towels at a hostel in {place}", "began during the humid monsoon in {place}", "started after playing football on wet fields in {place}"],
    atypical: "an itchy rash that got worse after using a steroid cream from a pharmacy",
    vital: ["lesion", 2, 9],
  },
  {
    id: "DX-0604", spec: "Dermatology", name: "Acute urticaria", age: [18, 70], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["itchy raised welts that come and go", "swelling of the lips at times", "symptoms that started after a new food or medicine"],
    regimens: [[m("Cetirizine", "10 mg", "Once daily", "14 days")], [m("Fexofenadine", "180 mg", "Once daily", "14 days")]],
    advice: "avoid the suspected food; keep a symptom diary; go to hospital at once if the tongue or throat swells",
    rxAdvice: "take the tablet at the same time each day; it may cause mild drowsiness",
    followUp: "2 weeks with the symptom diary", tests: "no tests unless it lasts more than six weeks",
    triggers: ["started after eating prawns at a restaurant in {place}", "began after taking a new painkiller bought in {place}", "started after eating hilsa at a family dinner in {place}"],
    atypical: "welts appearing only after a hot shower or exercise",
    vital: ["welts", 10, 40],
  },
  // SPEC-07 Orthopedics
  {
    id: "DX-0701", spec: "Orthopedics", name: "Lumbar muscle strain", age: [20, 65], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["low back pain after lifting something heavy", "stiffness when bending", "pain that eases with rest"],
    regimens: [[m("Ibuprofen", "400 mg", "Three times daily", "5 days"), m("Tolperisone", "150 mg", "Three times daily", "7 days")]],
    advice: "stay gently active; use a warm compress; lift with the knees bent",
    rxAdvice: "take ibuprofen after food; stop it if stomach pain develops",
    followUp: "2 weeks if the pain continues", tests: "no tests unless the pain lasts over six weeks",
    triggers: ["started after carrying a gas cylinder up the stairs in {place}", "began after moving furniture into a new flat in {place}", "started after lifting sacks at a warehouse in {place}"],
    atypical: "pain spreading to one buttock with no leg numbness",
    vital: ["pain", 5, 8],
  },
  {
    id: "DX-0702", spec: "Orthopedics", name: "Knee osteoarthritis", age: [50, 85], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["knee pain on the stairs", "stiffness in the morning for a few minutes", "a creaking knee"],
    regimens: [[m("Paracetamol", "1000 mg", "Three times daily", "1 month"), m("Diclofenac 1% gel", "Apply thin layer", "Three times daily", "14 days")]],
    advice: "do thigh-strengthening exercises daily; lose weight; avoid squatting and sitting cross-legged on the floor",
    rxAdvice: "do not take more than 3000 mg of paracetamol a day; wash hands after applying the gel",
    followUp: "6 weeks with physiotherapy", tests: "a knee X-ray",
    triggers: ["worse since moving to a building with no lift in {place}", "worse after a long sightseeing trip on foot in {place}", "worse since standing all day at a shop in {place}"],
    atypical: "sudden locking of the knee with little pain",
    vital: ["bmi", 27.0, 34.0],
  },
  {
    id: "DX-0703", spec: "Orthopedics", name: "Ankle sprain", age: [18, 55], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["a twisted ankle", "swelling around the ankle", "pain when walking"],
    regimens: [[m("Ibuprofen", "400 mg", "Three times daily", "5 days")]],
    advice: "rest, ice, compression, and elevation for 48 hours; use a crepe bandage",
    rxAdvice: "take ibuprofen after food",
    followUp: "1 week", tests: "an ankle X-ray if unable to bear weight",
    triggers: ["twisted during a football match in {place}", "twisted on a broken pavement in {place}", "twisted while stepping off a bus in {place}"],
    atypical: "pain mainly on the top of the foot rather than the ankle",
    vital: ["pain", 4, 8],
  },
  {
    id: "DX-0704", spec: "Orthopedics", name: "Adhesive capsulitis", age: [40, 70], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["a stiff shoulder for weeks", "being unable to raise the arm", "being unable to reach behind the back", "night pain in the shoulder"],
    regimens: [[m("Naproxen", "500 mg", "Twice daily", "14 days")]],
    advice: "start physiotherapy; do pendulum exercises daily; apply heat before exercise",
    rxAdvice: "take naproxen after meals; stop it if stomach pain or black stools occur",
    followUp: "4 weeks with a physiotherapy review", tests: "a shoulder X-ray and fasting glucose",
    triggers: ["began after a minor fall at home in {place}", "started after weeks of keeping the arm still after a sprain in {place}", "began gradually after a long illness in {place}"],
    atypical: "stiffness in both shoulders at the same time",
    vital: ["abduction", 60, 110],
  },
  // SPEC-08 Neurology
  {
    id: "DX-0801", spec: "Neurology", name: "Migraine", age: [18, 55], sex: "female65", chronic: true, febrile: false, canDefer: true,
    cues: ["a throbbing headache on one side", "light hurting the eyes", "nausea", "needing to lie in a dark room"],
    regimens: [[m("Sumatriptan", "50 mg", "As needed", "Until follow-up"), m("Propranolol", "40 mg", "Twice daily", "3 months")]],
    advice: "keep a headache diary; sleep and eat at regular times; limit screen time",
    rxAdvice: "take sumatriptan at the start of a headache and not more than two doses in 24 hours; take propranolol every day to prevent attacks",
    followUp: "3 months with the headache diary", tests: "no tests",
    triggers: ["worse since starting night shifts at a hospital in {place}", "attacks triggered by skipping meals while travelling in {place}", "worse since bright screens at a new job in {place}"],
    atypical: "flashing zigzag lights before the attacks and tingling in one hand",
    vital: ["headache_days", 4, 14],
  },
  {
    id: "DX-0802", spec: "Neurology", name: "Tension-type headache", age: [18, 65], sex: "any", chronic: false, febrile: false, canDefer: true,
    cues: ["band-like pressure around the head", "long hours at a screen", "stress", "neck tightness"],
    regimens: [[m("Paracetamol", "500 mg", "As needed", "7 days"), m("Amitriptyline", "10 mg", "At bedtime", "1 month")]],
    advice: "take screen breaks every hour; do neck stretches; sleep seven hours",
    rxAdvice: "limit paracetamol to three days a week; amitriptyline may cause a dry mouth and morning drowsiness",
    followUp: "1 month", tests: "no tests",
    triggers: ["started during a deadline month at an office in {place}", "began after a stressful house move to {place}", "worse since long daily commutes in {place}"],
    atypical: "a daily headache that is worst on waking after heavy painkiller use",
    vital: ["pain", 3, 6],
  },
  {
    id: "DX-0803", spec: "Neurology", name: "Peripheral neuropathy", age: [40, 85], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["burning in both feet", "tingling like pins and needles", "numbness in the toes", "symptoms worse at night"],
    regimens: [[m("Duloxetine", "30 mg", "Once daily", "3 months"), m("Methylcobalamin", "500 mcg", "Three times daily", "3 months")]],
    advice: "check the feet daily for cuts; wear soft closed shoes; keep blood sugar under control",
    rxAdvice: "take duloxetine after breakfast; do not stop it suddenly; mild nausea usually settles",
    followUp: "6 weeks", tests: "HbA1c, vitamin B12, and a nerve conduction study",
    triggers: ["noticed after long hours standing at a factory in {place}", "started after years of high sugar found at a health camp in {place}", "worse since walking barefoot at home in {place}"],
    atypical: "numbness in the hands before the feet",
    vital: ["monofilament", 3, 8],
  },
  {
    id: "DX-0804", spec: "Neurology", name: "Benign paroxysmal positional vertigo", age: [30, 80], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["brief spinning when turning in bed", "dizziness when looking up", "nausea with the spinning"],
    regimens: [[m("Betahistine", "16 mg", "Three times daily", "14 days")]],
    advice: "get up slowly from bed; avoid sudden head movements; repeat the Epley manoeuvre at home as shown",
    rxAdvice: "take betahistine with meals",
    followUp: "2 weeks", tests: "no tests",
    triggers: ["began after bumping the head on a rickshaw hood in {place}", "started after a long bus ride to {place}", "began after a viral cold in {place}"],
    atypical: "spinning only when lying on one side, with no nausea",
    vital: ["dix_hallpike", 0, 1],
  },
  // SPEC-09 ENT
  {
    id: "DX-0901", spec: "ENT", name: "Acute otitis media", age: [18, 60], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["ear pain", "a blocked ear after a cold", "mild fever", "muffled hearing"],
    regimens: [[m("Amoxicillin", "500 mg", "Three times daily", "7 days"), m("Paracetamol", "500 mg", "Every 6 hours as needed", "3 days")]],
    advice: "keep the ear dry; do not insert cotton buds",
    rxAdvice: "complete the amoxicillin course; take paracetamol for pain or fever",
    followUp: "1 week", tests: "no tests",
    triggers: ["started after swimming in a pond in {place}", "began after a cold during a trip to {place}", "started after a flight to {place}"],
    atypical: "ear pain with a small discharge and no fever",
    vital: ["temp", 99.6, 101.4],
  },
  {
    id: "DX-0902", spec: "ENT", name: "Allergic rhinitis", age: [18, 65], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["sneezing fits", "a runny nose", "itchy eyes", "symptoms worse with dust"],
    regimens: [[m("Fluticasone nasal spray", "2 sprays per nostril", "Once daily", "1 month"), m("Cetirizine", "10 mg", "Once daily", "14 days")]],
    advice: "avoid dust; wear a mask when cleaning; wash bedding weekly",
    rxAdvice: "aim the spray away from the centre of the nose; use it daily even when well",
    followUp: "1 month", tests: "no tests",
    triggers: ["worse since road construction began near home in {place}", "flares each spring in {place}", "worse since keeping a cat at home in {place}"],
    atypical: "a constantly blocked nose and snoring with little sneezing",
    vital: ["sneezes", 3, 15],
  },
  {
    id: "DX-0903", spec: "ENT", name: "Acute sinusitis", age: [18, 70], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["pressure over the cheeks and forehead", "a blocked nose", "thick nasal discharge for over ten days"],
    regimens: [[m("Amoxicillin-clavulanate", "625 mg", "Three times daily", "7 days"), m("Saline nasal spray", "2 sprays per nostril", "Three times daily", "7 days")]],
    advice: "use steam inhalation twice daily; drink warm fluids",
    rxAdvice: "take the antibiotic after food and complete the course; use the saline spray before other sprays",
    followUp: "10 days", tests: "no tests unless it recurs",
    triggers: ["started after a cold during a rainy week in {place}", "began after diving at a pool in {place}", "started after a dusty journey to {place}"],
    atypical: "toothache in the upper jaw as the main complaint",
    vital: ["temp", 99.4, 100.8],
  },
  {
    id: "DX-0904", spec: "ENT", name: "Acute tonsillitis", age: [18, 45], sex: "any", chronic: false, febrile: true, canDefer: false,
    cues: ["a sore throat", "painful swallowing", "fever", "swollen glands in the neck"],
    regimens: [[m("Phenoxymethylpenicillin", "500 mg", "Four times daily", "10 days"), m("Paracetamol", "500 mg", "Every 6 hours as needed", "3 days")]],
    advice: "gargle with warm salt water; eat soft food; drink plenty of fluids",
    rxAdvice: "take penicillin one hour before meals and complete all 10 days",
    followUp: "1 week", tests: "a throat swab if it recurs",
    triggers: ["began after an outbreak at a school in {place}", "started after cold drinks at a wedding in {place}", "began after shouting at a cricket match in {place}"],
    atypical: "one-sided throat pain with difficulty opening the mouth",
    vital: ["temp", 100.8, 103.0],
  },
  // SPEC-10 Ophthalmology
  {
    id: "DX-1001", spec: "Ophthalmology", name: "Allergic conjunctivitis", age: [18, 60], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["itchy watery red eyes", "both eyes affected", "symptoms worse in certain seasons"],
    regimens: [[m("Olopatadine 0.1% eye drops", "1 drop in each eye", "Twice daily", "14 days")]],
    advice: "avoid rubbing the eyes; use cool compresses; wear sunglasses outdoors",
    rxAdvice: "do not touch the dropper tip to the eye; wait 5 minutes between different drops",
    followUp: "2 weeks", tests: "no tests",
    triggers: ["started during the flowering season in {place}", "worse after cleaning a dusty storeroom in {place}", "began after visiting a farm in {place}"],
    atypical: "stringy discharge and swollen eyelids with little itch",
    vital: ["acuity", 0, 3],
  },
  {
    id: "DX-1002", spec: "Ophthalmology", name: "Bacterial conjunctivitis", age: [18, 70], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["a red eye", "sticky yellow discharge", "eyelids stuck together in the morning"],
    regimens: [[m("Moxifloxacin 0.5% eye drops", "1 drop in affected eye", "Three times daily", "7 days")]],
    advice: "wash hands often; do not share towels; stay away from work for two days",
    rxAdvice: "use the drops for the full 7 days; wash hands before and after each use",
    followUp: "1 week if not better", tests: "no tests",
    triggers: ["started after a family member in {place} had red eyes", "began after swimming at a public pool in {place}", "started during an outbreak at an office in {place}"],
    atypical: "discharge in one eye only with blurred vision",
    vital: ["acuity", 0, 3],
  },
  {
    id: "DX-1003", spec: "Ophthalmology", name: "Dry eye syndrome", age: [25, 80], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["gritty burning eyes", "long hours of screen time", "symptoms worse in air conditioning"],
    regimens: [[m("Carboxymethylcellulose 0.5% eye drops", "1 drop in each eye", "Four times daily", "1 month")]],
    advice: "look away from the screen every 20 minutes; blink often; use a humidifier",
    rxAdvice: "use the drops regularly even when the eyes feel fine",
    followUp: "1 month", tests: "a tear film break-up test",
    triggers: ["worse since moving to a new air-conditioned office in {place}", "began after long gaming sessions at home in {place}", "worse since night shifts at a call centre in {place}"],
    atypical: "eyes that water all day rather than feeling dry",
    vital: ["tbut", 3, 7],
  },
  {
    id: "DX-1004", spec: "Ophthalmology", name: "Hordeolum", age: [18, 60], sex: "any", chronic: false, febrile: false, canDefer: false,
    cues: ["a painful red lump at the edge of the eyelid", "swelling of the eyelid"],
    regimens: [[m("Chloramphenicol 1% eye ointment", "Apply thin layer", "Three times daily", "7 days")]],
    advice: "use a warm compress four times a day; do not squeeze the lump; avoid eye makeup",
    rxAdvice: "apply the ointment to the lid edge after the warm compress",
    followUp: "1 week", tests: "no tests",
    triggers: ["appeared after using old eye makeup in {place}", "began after a dusty motorbike ride in {place}", "appeared during a stressful week in {place}"],
    atypical: "a painless firm lump that has been present for weeks",
    vital: ["lid_lump", 3, 8],
  },
  // SPEC-11 Obstetrics and Gynecology
  {
    id: "DX-1101", spec: "Obstetrics and Gynecology", name: "Uncomplicated urinary tract infection", age: [18, 65], sex: "female", chronic: false, febrile: false, canDefer: false,
    cues: ["burning when passing urine", "going to the toilet often", "a lower belly ache"],
    regimens: [[m("Nitrofurantoin", "100 mg", "Twice daily", "5 days")]],
    advice: "drink at least two litres of water daily; do not hold urine for long",
    rxAdvice: "take nitrofurantoin with food; complete all 5 days; urine may turn dark yellow",
    followUp: "1 week if symptoms continue", tests: "a urine routine examination and culture",
    triggers: ["started after a long bus journey without toilet stops to {place}", "began during a hot week with little water intake in {place}", "started after a trip to {place}"],
    atypical: "cloudy urine and tiredness with no burning",
    vital: ["temp", 98.8, 100.2],
  },
  {
    id: "DX-1102", spec: "Obstetrics and Gynecology", name: "Polycystic ovary syndrome", age: [18, 35], sex: "female", chronic: true, febrile: false, canDefer: true,
    cues: ["irregular periods", "acne", "weight gain", "extra hair on the face"],
    regimens: [[m("Metformin", "500 mg", "Twice daily", "3 months")]],
    advice: "aim for 5% weight loss; exercise 150 minutes a week; reduce sugary drinks",
    rxAdvice: "take metformin with meals; mild stomach upset usually settles within a week",
    followUp: "3 months", tests: "a pelvic ultrasound and hormone profile",
    triggers: ["periods became irregular after moving to {place} for university", "noticed weight gain after starting a desk job in {place}", "noticed after a friend in {place} suggested testing"],
    atypical: "no periods for six months with no acne or weight gain",
    vital: ["bmi", 25.0, 33.0],
  },
  {
    id: "DX-1103", spec: "Obstetrics and Gynecology", name: "Primary dysmenorrhoea", age: [18, 30], sex: "female", chronic: false, febrile: false, canDefer: true,
    cues: ["painful cramps in the first days of each period", "missing work or classes because of the pain", "nausea with the pain"],
    regimens: [[m("Mefenamic acid", "500 mg", "Three times daily", "3 days")]],
    advice: "use a hot water bottle; do light exercise; keep a period diary",
    rxAdvice: "start mefenamic acid at the first sign of the period and take it after food",
    followUp: "3 months with the period diary", tests: "a pelvic ultrasound if the pain worsens",
    triggers: ["worse since starting exams at a college in {place}", "worse since a job with long standing hours in {place}", "worse after moving to a hostel in {place}", "worse since a stressful family move to {place}"],
    atypical: "pain spreading to the lower back and thighs with vomiting",
    vital: ["pain", 6, 9],
  },
  {
    id: "DX-1104", spec: "Obstetrics and Gynecology", name: "Vulvovaginal candidiasis", age: [18, 55], sex: "female", chronic: false, febrile: false, canDefer: false,
    cues: ["itching", "thick white discharge", "soreness"],
    regimens: [[m("Fluconazole", "150 mg", "Single dose", "1 day")]],
    advice: "wear cotton underwear; avoid scented soaps; keep the area dry",
    rxAdvice: "take the single fluconazole tablet with water",
    followUp: "2 weeks if it does not clear", tests: "no tests unless it recurs",
    triggers: ["started after a course of antibiotics taken in {place}", "began during the humid monsoon in {place}", "started after using a new scented soap bought in {place}"],
    atypical: "episodes returning four times a year",
    vital: ["glucose_random", 5.2, 7.8],
  },
  // SPEC-12 Psychiatry
  {
    id: "DX-1201", spec: "Psychiatry", name: "Generalized anxiety disorder", age: [18, 65], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["constant worry for months", "feeling restless", "tense muscles", "poor sleep"],
    regimens: [[m("Sertraline", "50 mg", "Once daily", "3 months")]],
    advice: "practise slow breathing daily; reduce tea and coffee; start counselling sessions",
    rxAdvice: "take sertraline in the morning; it takes 2 to 4 weeks to work; do not stop it suddenly",
    followUp: "4 weeks", tests: "thyroid function tests",
    triggers: ["worse since a family business loss in {place}", "began after witnessing a road accident in {place}", "worse since job insecurity at a company in {place}"],
    atypical: "stomach upset and headaches as the main complaints, with worry denied at first",
    vital: ["gad7", 10, 18],
  },
  {
    id: "DX-1202", spec: "Psychiatry", name: "Depressive episode", age: [18, 70], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["low mood for over three weeks", "no interest in usual activities", "poor sleep", "low energy"],
    regimens: [[m("Escitalopram", "10 mg", "Once daily", "3 months")]],
    advice: "keep a daily routine; walk outdoors daily; start counselling sessions; call 999 or come to the clinic at once if thoughts of self-harm appear",
    rxAdvice: "take escitalopram in the morning; it takes 2 to 4 weeks to work; do not stop it suddenly",
    followUp: "2 weeks", tests: "thyroid function tests and a complete blood count",
    triggers: ["began after losing a job in {place}", "started after the death of a parent in {place}", "began after moving away from family to {place}"],
    atypical: "sleeping too much and overeating rather than poor sleep",
    vital: ["phq9", 10, 19],
    mustInclude: "The patient denies thoughts of self-harm, and a safety plan with the emergency number 999 was discussed.",
  },
  {
    id: "DX-1203", spec: "Psychiatry", name: "Chronic insomnia", age: [25, 75], sex: "any", chronic: true, febrile: false, canDefer: true,
    cues: ["trouble falling asleep most nights", "waking up tired", "worry about sleep"],
    regimens: [[m("Melatonin", "3 mg", "At bedtime", "1 month")]],
    advice: "keep fixed sleep and wake times; avoid screens for an hour before bed; avoid tea after 4 PM",
    rxAdvice: "take melatonin one hour before bedtime",
    followUp: "4 weeks with a sleep diary", tests: "no tests",
    triggers: ["began after starting rotating shifts at a factory in {place}", "started after a noisy construction site opened near home in {place}", "began after a newborn arrived in the family in {place}"],
    atypical: "waking at 3 AM every night and being unable to sleep again",
    vital: ["isi", 15, 24],
  },
  {
    id: "DX-1204", spec: "Psychiatry", name: "Panic disorder", age: [18, 50], sex: "any", chronic: true, febrile: false, canDefer: false,
    cues: ["sudden attacks of a racing heart", "breathlessness during attacks", "a fear of dying", "normal heart tests"],
    regimens: [[m("Sertraline", "25 mg", "Once daily", "1 month"), m("Propranolol", "10 mg", "As needed", "1 month")]],
    advice: "practise slow breathing during attacks; reduce caffeine; start counselling sessions",
    rxAdvice: "take sertraline every morning; use propranolol only during attacks and not more than three times a day",
    followUp: "4 weeks", tests: "an ECG and thyroid function tests",
    triggers: ["first attack happened in a crowded lift in {place}", "attacks began after a traffic accident in {place}", "first attack happened at a busy market in {place}"],
    atypical: "attacks that wake the patient from sleep",
    vital: ["attacks", 3, 12],
  },
];

export const MEDICINE_NAMES = [...new Set(DIAGNOSES.flatMap((d) => d.regimens.flat().map((med) => med.name)))];

export const OCCUPATIONS = [
  "rickshaw puller", "garment factory worker", "bank officer", "schoolteacher", "university student",
  "software developer", "shopkeeper", "bus driver", "CNG auto-rickshaw driver", "security guard",
  "nurse", "homemaker", "retired civil servant", "journalist", "restaurant cook",
  "delivery rider", "construction worker", "tailor", "pharmacist", "accountant",
  "call centre agent", "farmer", "fisherman", "police constable", "electrician",
  "lawyer", "graphic designer", "textile engineer", "sales representative", "madrasa teacher",
  "beautician", "mobile phone repair technician", "NGO field officer", "hotel receptionist", "cricket coach",
  "photographer", "architect", "garment merchandiser", "ride-share driver", "office cleaner",
];

export const PLACES = [
  "Mirpur", "Uttara", "Dhanmondi", "Mohammadpur", "Gulshan", "Banani", "Badda", "Rampura", "Motijheel",
  "Old Dhaka", "Jatrabari", "Keraniganj", "Savar", "Gazipur", "Tongi", "Narayanganj", "Tejgaon", "Farmgate",
  "Khilgaon", "Bashundhara", "Shyamoli", "Lalbagh", "Wari", "Kamrangirchar", "Chattogram", "Sylhet",
  "Rajshahi", "Khulna", "Barishal", "Cumilla", "Mymensingh", "Bogura", "Rangpur", "Cox's Bazar", "Tangail",
  "Faridpur", "Jashore", "Noakhali", "Kushtia", "Sirajganj",
];

export const COMORBIDITIES = ["Essential hypertension", "Type 2 diabetes mellitus", "Bronchial asthma", "Hypothyroidism"];

export const NAMES = {
  muslimMale: ["Abdul", "Rahim", "Karim", "Jamal", "Kamal", "Hasan", "Hossain", "Rafiq", "Shafiq", "Tariq", "Nazmul", "Mizanur", "Aminul", "Shahidul", "Anwar", "Masud", "Sohel", "Rubel", "Sajjad", "Fahim", "Nayeem", "Rakib", "Shakil", "Mamun", "Jahid", "Rashed", "Sabbir", "Arif", "Imtiaz", "Tanvir", "Mehedi", "Ashraf", "Golam", "Monir", "Selim", "Babul", "Harun", "Ibrahim", "Yusuf", "Farhan"],
  muslimFemale: ["Ayesha", "Fatema", "Rahima", "Salma", "Shahana", "Nasima", "Rehana", "Parvin", "Taslima", "Nargis", "Sultana", "Rokeya", "Shirin", "Farida", "Jesmin", "Morium", "Sumaiya", "Tania", "Mitu", "Lipi", "Rupa", "Shapla", "Nadia", "Sadia", "Tahsin", "Anika", "Nusrat", "Mahiya", "Samira", "Afsana", "Jannat", "Sharmin", "Lamia", "Rumana", "Kulsum", "Hasina", "Rabeya", "Sabina", "Bilkis", "Dilruba"],
  muslimSurname: ["Ahmed", "Hossain", "Rahman", "Islam", "Uddin", "Alam", "Akter", "Begum", "Khan", "Chowdhury", "Miah", "Sarkar", "Talukder", "Bhuiyan", "Sheikh", "Mollah", "Haque", "Karim", "Siddique", "Mahmud", "Kabir", "Hasan", "Sultana", "Khatun", "Mondal", "Howlader", "Patwary", "Majumder", "Faruque", "Awal"],
  hinduMale: ["Sanjay", "Pradip", "Ratan", "Gopal", "Amit", "Subrata", "Tapan", "Bikash", "Uttam", "Nirmal", "Shyamal", "Dipak"],
  hinduFemale: ["Priya", "Rina", "Mita", "Shikha", "Anjali", "Puja", "Sumitra", "Kakoli", "Mousumi", "Laxmi", "Rupali", "Sraboni"],
  hinduSurname: ["Das", "Saha", "Roy", "Dey", "Ghosh", "Paul", "Sarkar", "Biswas", "Kundu", "Mitra", "Bose", "Datta"],
};

export const PLAN_NOTES = {
  continue: "chronic follow-up: continue current medicines, no new prescription issued",
  tests: (dx) => `tests ordered before starting treatment: ${dx.tests}`,
  lifestyle: "lifestyle and self-care advice only, no medicine needed at this stage",
  referral: (spec) => `referral to ${spec} in this clinic for further assessment`,
};

// General FAQ intents FAQI-001..FAQI-070. Facts come from SPEC.md section 4.
export const GENERAL_FAQ = [
  ["Accounts", "how do I create an account", ["sign up in the CareBridge app with email and password or with Google", "new accounts are patient accounts"]],
  ["Accounts", "can I sign in with Google", ["you can sign in with your Google account", "use the Sign in with Google button on the login page"]],
  ["Accounts", "I cannot sign in to my account", ["contact reception at +880 1711-000000", "reception is open Saturday to Thursday, 9:00 AM to 5:00 PM"]],
  ["Accounts", "how do I update my profile details", ["open My Profile in the app", "you can update details such as phone, address, allergies, and emergency contact"]],
  ["Accounts", "who can see my medical records", ["patients see only their own appointments, prescriptions, and bills", "doctors see the records of their own patients", "reception staff can see all records to run the clinic"]],
  ["Accounts", "can my family share one account", ["each person needs their own account", "family members cannot share one account"]],
  ["Accounts", "how are doctor and receptionist roles assigned", ["new sign-ups are patient accounts", "doctor and receptionist roles are assigned by reception"]],
  ["Accounts", "how do I delete my account", ["contact reception to delete your account", "the reception phone is +880 1711-000000"]],
  ["Booking", "how do I book an appointment", ["open Book Appointment in the app", "choose a doctor, a date, and a time slot", "enter the reason for the visit", "the booking starts with status requested"]],
  ["Booking", "what information do I need to book", ["the doctor", "the date", "the time slot", "a short reason for the visit"]],
  ["Booking", "how do I choose the right doctor", ["the doctor list shows each doctor's specialization, fee, and working days", "the assistant can suggest a specialization but it is not medical advice"]],
  ["Booking", "how do I choose a time slot", ["only the doctor's working days and listed slots can be booked", "a slot that is already booked cannot be chosen"]],
  ["Booking", "what does requested status mean", ["requested means reception has not confirmed the booking yet", "reception confirms it within the same working day"]],
  ["Booking", "how will I know my appointment is confirmed", ["the status changes to confirmed in My Appointments", "you receive a reminder within the 24 hours before the visit"]],
  ["Booking", "how long does confirmation take", ["reception confirms requested bookings within the same working day", "working days are Saturday to Thursday"]],
  ["Booking", "the slot I want is already booked", ["a booked slot cannot be chosen", "you can join the waitlist for that doctor and day"]],
  ["Booking", "can I book an appointment for someone else", ["each patient books from their own account", "family members need their own accounts"]],
  ["Booking", "do you accept walk-in patients", ["walk-ins are seen only if a slot is free", "booking in the app is preferred"]],
  ["Booking", "what should I bring to my first visit", ["photo ID", "previous prescriptions", "recent test reports"]],
  ["Booking", "what happens if I arrive late", ["arriving more than 15 minutes late may require rescheduling"]],
  ["Cancel and reschedule", "how do I cancel an appointment", ["open My Appointments and cancel the appointment", "you can cancel while the status is requested or confirmed"]],
  ["Cancel and reschedule", "which appointments can I cancel", ["only requested or confirmed appointments can be cancelled", "completed appointments cannot be cancelled"]],
  ["Cancel and reschedule", "is there a cancellation fee", ["there is no cancellation fee"]],
  ["Cancel and reschedule", "how do I reschedule an appointment", ["open My Appointments and choose reschedule", "pick a new future date on the doctor's working day and slot"]],
  ["Cancel and reschedule", "what are the rules for rescheduling", ["only requested or confirmed appointments can be rescheduled", "the new date must be in the future", "the new slot must be one of the doctor's slots on a working day"]],
  ["Cancel and reschedule", "can I change a completed appointment", ["completed appointments cannot be cancelled or rescheduled", "book a new follow-up appointment instead"]],
  ["Cancel and reschedule", "what counts as a no-show", ["a confirmed appointment not completed 1 hour after its start time is flagged as a possible no-show"]],
  ["Cancel and reschedule", "what happens after I miss an appointment", ["reception reviews the possible no-show", "reception may contact you to rebook"]],
  ["Waitlist", "what is the waitlist", ["the waitlist lets you wait for a full day or slot with a doctor", "when a slot is freed the next patient on the waitlist gets an offer"]],
  ["Waitlist", "how do I join the waitlist", ["join the waitlist when the slot or day you want is full", "you can have one open waitlist entry per doctor and day"]],
  ["Waitlist", "how will I know I got a waitlist offer", ["you get a notification under the bell icon", "the offer also appears in My Appointments"]],
  ["Waitlist", "how long do I have to accept a waitlist offer", ["120 minutes", "accept the offer in My Appointments", "the offer expires if not accepted in time", "the slot then passes to the next patient on the waitlist"]],
  ["Waitlist", "my waitlist offer expired", ["an offer not accepted within 120 minutes expires", "the slot passes to the next patient on the waitlist", "you can join the waitlist again"]],
  ["Waitlist", "how do I leave the waitlist", ["you can leave the waitlist at any time from My Appointments"]],
  ["Notifications", "will I get a reminder before my appointment", ["a reminder is sent within the 24 hours before a confirmed appointment", "reminders appear under the bell icon in the app"]],
  ["Notifications", "where do I see my notifications", ["notifications appear under the bell icon in the app"]],
  ["Notifications", "I did not get a reminder", ["reminders are sent only for confirmed appointments", "check that your booking status is confirmed"]],
  ["Notifications", "do you send SMS reminders", ["the clinic does not send SMS reminders", "reminders appear as in-app notifications under the bell icon"]],
  ["Notifications", "will I be notified about waitlist offers", ["you get a notification when a waitlist slot is offered", "you have 120 minutes to accept it"]],
  ["Prescriptions", "where can I find my prescription", ["open My Prescriptions in the app"]],
  ["Prescriptions", "when will my prescription appear", ["the doctor writes the prescription at the end of the consultation", "it appears in My Prescriptions once the appointment is completed"]],
  ["Prescriptions", "what does a prescription contain", ["the date", "the doctor", "the diagnosis", "each medicine with dosage, frequency, and duration", "the doctor's notes"]],
  ["Prescriptions", "can one visit have more than one prescription", ["each appointment has one prescription"]],
  ["Prescriptions", "how do I get a refill", ["book a follow-up appointment for a refill"]],
  ["Prescriptions", "there is an error on my prescription", ["contact reception to report an error on a prescription"]],
  ["Prescriptions", "can the AI assistant change my medicines", ["the assistant cannot change medicines", "only your doctor can change a prescription"]],
  ["Prescriptions", "I have side effects from my medicine", ["contact the clinic or your doctor about side effects", "for emergencies call 999"]],
  ["Billing", "when is my bill created", ["reception creates the bill after your visit"]],
  ["Billing", "how do I pay my bill", ["pay at reception after the visit", "payment methods are cash, card, or mobile banking"]],
  ["Billing", "which payment methods do you accept", ["cash", "card", "mobile banking"]],
  ["Billing", "can I pay by mobile banking", ["mobile banking is accepted"]],
  ["Billing", "can I pay by card", ["card payment is accepted"]],
  ["Billing", "what do unpaid and paid mean on my bill", ["unpaid means the bill has not been paid yet", "paid means the payment has been recorded"]],
  ["Billing", "how do I get an invoice", ["ask reception for your invoice", "the AI assistant can show your bills"]],
  ["Billing", "why do consultation fees differ", ["the consultation fee depends on the doctor", "senior consultants charge more"]],
  ["Billing", "where can I see a doctor's fee", ["each doctor's fee is shown in the doctor list when booking"]],
  ["Billing", "do I pay in advance and can I get a refund", ["payment is made after the visit", "there is no advance payment and no refund process"]],
  ["Clinic info", "what are your opening hours", ["Saturday to Thursday, 9:00 AM to 5:00 PM"]],
  ["Clinic info", "are you open on Friday", ["the clinic is closed on Friday and public holidays"]],
  ["Clinic info", "where is the clinic", ["House 27, Road 9/A, Dhanmondi, Dhaka 1209"]],
  ["Clinic info", "what is the clinic phone number", ["+880 1711-000000"]],
  ["Clinic info", "is there parking at the clinic", ["only limited street parking is available"]],
  ["Clinic info", "is the clinic wheelchair accessible", ["there is a wheelchair ramp and a lift at the entrance"]],
  ["Clinic info", "which languages do your staff speak", ["reception staff speak Bangla and English"]],
  ["Clinic info", "what should I do in an emergency", ["the clinic is not an emergency service", "call 999 or go to the nearest hospital emergency department"]],
  ["AI assistant", "what can the AI assistant do", ["look up your appointments, prescriptions, bills, and profile", "prepare bookings, cancellations, and reschedules as proposal cards"]],
  ["AI assistant", "is the AI assistant giving medical advice", ["the assistant gives general information and specialization guidance only", "it is not medical advice and does not diagnose"]],
  ["AI assistant", "can the AI assistant book for me", ["the assistant prepares a booking as a proposal card", "nothing changes until you press Confirm"]],
  ["AI assistant", "are my chats with the assistant private", ["your chats are private to your account"]],
  ["AI assistant", "what if the AI assistant makes a mistake", ["do not press Confirm on a wrong proposal card", "contact reception if something looks wrong"]],
];
